
title: Jerrica Raemer

baseurl: ""
url: "https://jerricaraemer.github.io"
theme: jekyll-theme-modernist
markdown: kramdown

nav:
  - name: Home
    link: /
  - name: About
    link: /about/
  - name: Skills & Education
    link: /skills/
  - name: Career
    link: /career/
  - name: Portfolio
    link: /portfolio/
  - name: Volunteer
    link: /volunteer/
  - name: Contact
    link: /contact/
